name = "epoll"
description = "Linux epoll binding"
version = "0.1.0"
licenses = "BSD-3-Clause"
tags = ["linux", "epoll", "net"]
website = "https://github.com/JeremyGrosser/epoll-ada"

authors = ["Jeremy Grosser"]
maintainers = ["Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["JeremyGrosser"]
